import datetime
import re
import os
import pandas as pd

wildcard_constraints:
  chr = "chr[0-9X]{1,2}"

max_time = 240

def get_mem_mb(wildcards, threads):
    return threads * 3420

def get_permute_time(wildcards, threads):
    return min(max_time, 300+3*((int(wildcards.draws)/300)*3600)/int(threads))

metadata_daf = pd.read_csv('resources/gwas/metadata/metadata_all_fields.tsv', sep = '\t')

trait_pairs = ["pid_acne",
"pid_pbc",
"pid_addi",
"pid_agran",
"pid_glom",
"pid_polymyal",
"pid_all-conj",
"pid_gout",
"pid_polyp",
"pid_all-urt",
"pid_hyperpara",
"pid_ank-spond",
"pid_hyperthy",
"pid_psc",
"pid_hypothy",
"pid_pso-arthr",
"pid_pso",
"pid_ra",
"pid_asthma",
"pid_igad",
"pid_rheum-fev",
"pid_rhin",
"pid_rosacea",
"pid_coeliac",
"pid_sarc",
"pid_sjogren",
"pid_jia",
"pid_sle",
"pid_crohns",
"pid_lada",
"pid_spondylo",
"pid_derm-ecz",
"pid_licp",
"pid_still",
"pid_desq",
"pid_licsa",
"pid_divert",
"pid_sys-scl",
"pid_t1d",
"pid_dyschr-vit",
"pid_ms",
"pid_thy",
"pid_endomet",
"pid_myas",
"pid_uc-delange",
"pid_ent-col",
"pid_eos-eso",
"pid_igg",
"pid_iga",
"pid_igm",
"pid_pid-finngen"]

impermutable_trait_pairs = ['pid_ra', 'pid_psc', 'pid_uc-delange']

permutable_trait_pairs = [x for x in trait_pairs if x not in impermutable_trait_pairs]

ukbb_traits = ["asthma",
               "rhin",
               "gout"]

finngen_traits = ["hyperthy",
                  "agran",
                  "sarc",
                  "hyperpara",
                  "hypothy",
                  "glom",
                  "all-conj",
                  "polyp",
                  "ent-col",
                  "acne",
                  "derm-ecz",
                  "licp",
                  "licsa",
                  "rosacea",
                  "all-urt",
                  "ank-spond",
                  "polymyal",
                  "sjogren",
                  "endomet",
                  "pso-arthr",
                  "spondylo",
                  "still",
                  "thy",
                  "pid-finngen"]

misc_traits = ["pbc",
               "addi",
               "psc",
               "ra",
               "igad",
               "rheum-fev",
               "coeliac",
               "jia",
               "sle",
               "crohns",
               "lada",
               "sys-scl",
               "t1d",
               "ms",
               "myas",
               "uc-delange",
               "eos-eso",
               "igg",
               "iga",
               "igm",
               "pid"]

include: 'rules/1000g_reference.smk'
include: 'rules/gwas.smk'
include: 'rules/gps.smk'
include: 'rules/cfdr.smk'
include: 'rules/sumher.smk'
include: 'rules/export.smk'
include: 'rules/gps_paper.smk'
